language: ruby
rvm:
  - 2.2.5

# Follows advice of https://github.com/gjtorikian/html-proofer/wiki/Using-HTMLProofer-From-Ruby-and-Travis  
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Follows advice of https://github.com/jekyll/jekyll/issues/3480
install:
  - gem install jekyll
  - gem install html-proofer

script:
  - jekyll build
  - htmlproofer _site
